export const REPOSITORY_NAME = {
  react: "web-react",
  vue: "web-vue",
  theme: "theme",
  material: "material",
  iconBox: "icon-box",
  demo: "data",
};

export const ORGANIZATION_NAME = "Geek-photography"; //'arco-design'

export const ARCO_ISSUE_MARK =
  "<!-- generated by arco-issue. DO NOT REMOVE -->";

export const ISSUE_TEMPLATE = [
  "Basic Info",
  "预期结果",
  "复现步骤",
  "依赖包名 及 版本",
  "复现步骤",
];

export const COMMENT_WORDS = {
  invalidIssue:
    "Sorry, we have format requirements for the issue. Your issue will be closed.\nRecommend to use [new-issue](https://new-issue.vuejs.org/?repo=vuejs/vue)",
};
